### ISSUE TITLE
Error on startup when Tuya devices not present

### ISSUE THREAD

**Issue by littlepunks** [littlepunks/autohome#7]
(node:974) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /home/pi/autohome/node_modules/tuyapi/index.js:619:13
    at Timeout._onTimeout (/home/pi/autohome/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by littlepunks** [comment]
Updated modules don't surface the same error.
